import { strict as assert } from "node:assert";
import { access, readFile } from "node:fs/promises";

const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const ignore = await readFile(new URL("../../.gitignore", import.meta.url), "utf8");
const workflow = await readFile(new URL("../../.github/workflows/release-windows.yml", import.meta.url), "utf8");
const mainProcess = await readFile(new URL("../electron/main.cjs", import.meta.url), "utf8");
const preload = await readFile(new URL("../electron/preload.cjs", import.meta.url), "utf8");
const indexHtml = await readFile(new URL("../index.html", import.meta.url), "utf8");
const brandSvg = await readFile(new URL("../public/branding/family-circle.svg", import.meta.url), "utf8");

assert.equal(packageJson.main, "electron/main.cjs");
assert.equal(packageJson.build.appId, "ru.teru1337.familytree");
assert.equal(packageJson.build.productName, "Семейное древо");
assert.equal(packageJson.build.win.icon, "build-resources/family-circle.ico");
assert.deepEqual(packageJson.build.extraResources, [{ from: "build-resources/family-circle.ico", to: "family-circle.ico" }]);
assert.deepEqual(packageJson.build.win.target[0].arch, ["x64"]);
assert.equal(packageJson.dependencies["electron-updater"], "6.8.9");
assert.equal(packageJson.build.publish.provider, "github");
assert.equal(packageJson.build.publish.owner, "teru1337");
assert.equal(packageJson.build.publish.repo, "family-tree-desktop");
assert.equal(packageJson.build.win.verifyUpdateCodeSignature, false);
assert.equal(packageJson.build.nsis.oneClick, false);
assert.equal(packageJson.build.nsis.createDesktopShortcut, true);
assert.equal(packageJson.build.nsis.createStartMenuShortcut, true);
assert.match(packageJson.scripts["dist:win"], /electron-builder/);
assert.match(ignore, /release/);
assert.match(workflow, /tags:\s*[\r\n]+\s+-\s+["']v\*["']/);
assert.match(workflow, /--publish never/);
assert.match(workflow, /gh release create/);
assert.match(workflow, /latest\.yml/);
assert.match(workflow, /GH_TOKEN:/);
assert.match(mainProcess, /autoUpdater\.checkForUpdates/);
assert.match(mainProcess, /autoUpdater\.downloadUpdate/);
assert.match(mainProcess, /getAppIconPath\(\)/);
assert.match(mainProcess, /icon: getAppIconPath\(\)/);
assert.match(mainProcess, /quitAndInstall\(true, true\)/);
assert.match(mainProcess, /mainWindow\.maximize\(\)/);
assert.match(preload, /family-tree-update-status/);
assert.match(indexHtml, /branding\/family-circle\.svg/);
assert.match(brandSvg, /Круг поколений/);
await access(new URL("../electron/main.cjs", import.meta.url));
await access(new URL("../electron/preload.cjs", import.meta.url));
await access(new URL("../public/branding/family-circle.png", import.meta.url));
await access(new URL("../build-resources/family-circle.ico", import.meta.url));
console.log("Windows packaging configuration ok: Electron + NSIS x64");
