import { strict as assert } from "node:assert";
import { access, readFile } from "node:fs/promises";

const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const ignore = await readFile(new URL("../../.gitignore", import.meta.url), "utf8");
const workflow = await readFile(new URL("../../.github/workflows/release-windows.yml", import.meta.url), "utf8");
const mainProcess = await readFile(new URL("../electron/main.cjs", import.meta.url), "utf8");
const preload = await readFile(new URL("../electron/preload.cjs", import.meta.url), "utf8");

assert.equal(packageJson.main, "electron/main.cjs");
assert.equal(packageJson.build.appId, "ru.teru1337.familytree");
assert.equal(packageJson.build.productName, "Семейное древо");
assert.deepEqual(packageJson.build.win.target[0].arch, ["x64"]);
assert.equal(packageJson.dependencies["electron-updater"], "6.8.9");
assert.equal(packageJson.build.publish.provider, "github");
assert.equal(packageJson.build.publish.owner, "teru1337");
assert.equal(packageJson.build.publish.repo, "family-tree-desktop");
assert.equal(packageJson.build.win.signExecutable, true);
assert.equal(packageJson.build.win.verifyUpdateCodeSignature, true);
assert.equal(packageJson.build.nsis.oneClick, false);
assert.equal(packageJson.build.nsis.createDesktopShortcut, true);
assert.equal(packageJson.build.nsis.createStartMenuShortcut, true);
assert.match(packageJson.scripts["dist:win"], /electron-builder/);
assert.match(ignore, /release/);
assert.match(workflow, /tags:\s*[\r\n]+\s+-\s+["']v\*["']/);
assert.match(workflow, /--publish never/);
assert.match(workflow, /WIN_CSC_LINK/);
assert.match(workflow, /WIN_CSC_KEY_PASSWORD/);
assert.match(workflow, /Get-AuthenticodeSignature/);
assert.match(workflow, /publisherName/);
assert.match(workflow, /gh release create/);
assert.match(workflow, /latest\.yml/);
assert.match(workflow, /GH_TOKEN:/);
assert.match(mainProcess, /autoUpdater\.checkForUpdates/);
assert.match(mainProcess, /autoUpdater\.downloadUpdate/);
assert.match(preload, /family-tree-update-status/);
await access(new URL("../electron/main.cjs", import.meta.url));
await access(new URL("../electron/preload.cjs", import.meta.url));
console.log("Windows packaging configuration ok: Electron + NSIS x64");
